---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ namespace }}
  name: pv-nfs-pv0
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    server: mum00aqm
    path: /u02/pvs/pv0
...

---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ namespace }}
  name: pv-nfs-pv1
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    server: mum00aqm
    path: /u02/pvs/pv1
...


---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ namespace }}
  name: pv-nfs-pv2
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    server: mum00aqm
    path: /u02/pvs/pv2
...


---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ namespace }}
  name: pv-nfs-pv3
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    server: mum00aqm
    path: /u02/pvs/pv3
...


---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ namespace }}
  name: pv-nfs-pv4
spec:
  storageClassName: manual
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  nfs:
    server: mum00aqm
    path: /u02/pvs/pv4
...
