# task goes here
---
- name: "Creating a Nfs shared directory"
  file:
    path: /u02/pvs/{{ item }}
    state: directory
    recurse: yes
  with_items:
  - pv0
  - pv1
  - pv2
  - pv3
  - pv4

- name: "Ensure nfs packages is installed"
  yum:
    name: 
    - nfs-utils
    - rpcbind
    state: present  

- name: "Manage configuration and restart if required"
  shell: |
    NFS_CONF_DIR='/etc/exports'
    ### Add entry in etc export file and restart if entry added
    grep 'pvs' $NFS_CONF_DIR >/dev/null || ( sed -i '$ a\/u02/pvs *(rw,sync,no_root_squash,nohide)' $NFS_CONF_DIR && ( systemctl restart nfs && exportfs ) )
     
