---

- name: "Installing Kubernetes python client for ansible"
  hosts: ansible_node
  gather_facts: False
  roles:
  - common

- name: "Cloud Comp OMS Deployment on kunernetes Cluster"
  hosts: k8s_master
  gather_facts: False
  roles:
  - preccoms
  - database
  - ccoms
