apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfg-ms
  namespace: {{ namespace }}
  labels:
    app: cfg-ms
spec:
  replicas: {{ APPS.CONFIG.REPLICA }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: cfg-ms
  template:
    metadata:
      labels:
        app: cfg-ms
    spec:
      containers:
      - name: cfg-ms
        image: '{{ IMAGEPREFIX }}:{{ APPS.CONFIG.IMAGE }}'
        imagePullPolicy: Always
        ports:
        - containerPort: {{ APPS.CONFIG.CONTAINERPORT }}
        env:
        - name: app.profile
          value: {{ PROFILE }}
